### PR TITLE
Build frameworks for iOS / OSX

### PR DESCRIPTION
**Pull request by grgcombs**
- Added support for Carthage
- Specs are updated to use Quick/Nimble for BDD
- Does not include targets for tvOS or watchOS yet.  Those platforms aren't fully supported in the current versions of Quick/Nimble.
- Added a Getting Started section to the readme
- Added a .gitignore
- Closes #51 in favor of of this, as this retains BDD specs.

### CODE REVIEW

**Comment by grgcombs** [comment]
Finally!  God, Travis can be such a nightmare -- and it sucks that we have to publicly push to have it run again with possible fixes.

**Comment by robb** [comment]
Looks great, thanks for spending the time and effort. :sparkling_heart: 

One more thing: could you replace the `#import <Asterism/Asterism.h>` with `@import Asterism` wherever possible?

**Comment by grgcombs** [comment]
Hmm -- doesn't seem to work quite right.  iOS will run the specs fine.  However with OS X, the specs won't compile with `@import Asterism;` -- I couldn't find any combination of build settings that would affectively correct this.

```
CompileC Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/Objects-normal/x86_64/ASTFlattenSpec.o Specs/ASTFlattenSpec.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/greg/GitHub/Asterism
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/greg/GitHub/Asterism/Builds/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/greg/GitHub/Asterism/Builds/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.9 -g -Wno-sign-conversion -iquote /Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/AsterismSpecs-generated-files.hmap -I/Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/AsterismSpecs-own-target-headers.hmap -I/Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/AsterismSpecs-all-target-headers.hmap -iquote /Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/AsterismSpecs-project-headers.hmap -I/Users/greg/GitHub/Asterism/Builds/Build/Products/Debug/include -I/Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/DerivedSources/x86_64 -I/Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/DerivedSources -F/Users/greg/GitHub/Asterism/Builds/Build/Products/Debug -F/Applications/Xcode.app/Contents/Developer/Library/Frameworks -F/Users/greg/GitHub/Asterism/Carthage/Build/Mac -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -include /Users/greg/GitHub/Asterism/Builds/Build/Intermediates/PrecompiledHeaders/Specs-Prefix-entwlqkfxcbyorgpllydowgwgcvp/Specs-Prefix.pch -MMD -MT dependencies -MF /Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/Objects-normal/x86_64/ASTFlattenSpec.d --serialize-diagnostics /Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/Objects-normal/x86_64/ASTFlattenSpec.dia -c /Users/greg/GitHub/Asterism/Specs/ASTFlattenSpec.m -o /Users/greg/GitHub/Asterism/Builds/Build/Intermediates/Asterism.build/Debug/AsterismSpecs-OSX.build/Objects-normal/x86_64/ASTFlattenSpec.o

/Users/greg/GitHub/Asterism/Specs/ASTFlattenSpec.m:9:9: fatal error: module 'Asterism' not found
@import Asterism;
 ~~~~~~~^~~~~~~~
1 error generated.
```

**Comment by robb** [comment]
Weird, then let's leave that for another day.

**Comment by robb** [comment]
Thanks again!

**Comment by grgcombs** [comment]
My pleasure!

**Pull request merged**
